#pragma once
#include <iostream>
#include <cassert>
#include <unordered_map>
#include <string_view>
#include <array>
#include <vector>
#include <math.h>    
#include "DxLib.h"
#include "EffekseerForDXLib.h"
#include "Calculation.h"
#include "Camera.h"
#include "Effect.h"
#include "EnemyBullet.h"
#include "EnemyCircleAttack.h"
#include "EnemyBreath.h"
#include "Enemy.h"
#include "EnemyManager.h"
#include "Object.h"
#include "ObjectManager.h"
#include "Input.h"
#include "Player.h"
#include "Map.h"
#include "Common.h"
#include "GameUI.h"
#include "BlackOut.h"
#include "BaseScene.h"
#include "Game.h"
#include "GameClear.h"
#include "Title.h"
#include "GameOver.h"
#include "SceneManager.h"